version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: laravel_app
        volumes:
            - laravel_storage:/var/www/storage
        working_dir: /var/www
        command: php artisan serve --host=0.0.0.0 --port=5000
        ports:
            - "5000:5000"

    composer:
        image: composer:latest
        container_name: composer
        command: composer install

volumes:
  laravel_storage:
